monitor.alsa.rules = [
  {
    matches = [
      {
        # Logitech webcam
        alsa.components = "USB046d:0825"
      }
    ]
    actions = {
      update-props = {
        node.disabled = true
      }
    }
  }
]
