[terminal]
vt = 1

[default_session]
command = "agreety --cmd 'uwsm start -g -1 -- river -log-level debug -c \"uwsm finalize\"'"
user = "greeter"

[initial_session]
command = "uwsm start -g -1 -- river -log-level debug -c 'uwsm finalize'"
user = "pkaplan"
