#!/bin/sh
set -eu

# terminal
riverctl map normal Super Return spawn $TERMINAL

dbus-update-activation-environment --systemd WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP

#WAYLOCK="waylock -fork-on-lock -ignore-empty-password -init-color 0xcba6f7"
WAYLOCK="swaylock"

# autostart
launch -rl swayidle -w before-sleep \"$WAYLOCK\" timeout 300 \"$WAYLOCK\"
launch -rl waybar
launch nm-applet --indicator
launch blueman-applet
launch -l way-displays
launch wlsunset -l 47.6 -L 9.4
XDG_CURRENT_DESKTOP=sway launch flameshot
launch /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
launch poweralertd
launch rbw-agent

# execute this file
riverctl map normal Super+Shift C spawn "$HOME/.config/river/init"

# keyboard
riverctl keyboard-layout -options caps:escape_shifted_capslock eu

# menu
riverctl map normal Super D spawn "fuzzel -w 80 --list-executables-in-path"

# power management
riverctl map normal Super Escape spawn "$WAYLOCK"
riverctl map normal Super+Shift+Control X exit
riverctl map normal Super+Shift Z spawn "systemctl suspend"
riverctl map locked Super+Shift Z spawn "systemctl suspend"
for mode in normal locked; do
    riverctl map $mode Super+Shift+Control Z spawn "systemctl poweroff"
    riverctl map $mode Super+Alt+Shift+Control Z spawn "systemctl reboot"
done

# waybar toggle
riverctl map normal Super+Control B spawn "killall -SIGUSR1 waybar"

# screenshot
riverctl map normal Super S spawn "XDG_CURRENT_DESKTOP=sway flameshot gui"
riverctl map normal None Print spawn "XDG_CURRENT_DESKTOP=sway flameshot gui"

# screen recording
riverctl map normal Super+Shift S spawn '{
    set -eu
    if ps -C wf-recorder; then
        VID="$(pgrep -xa wf-recorder | cut -d" " -f4)"
        killall -SIGINT wf-recorder
        wl-copy < "$VID"
        notify-send "Screen recording stopped." "Saved as $VID and copied to clipboard."
    else
        VID="$HOME/Pictures/Screenshots/rec_$(date +%Y%m%d_%Hh%Mm%S.%2Ns).mp4"
        if AREA="$(slurp)"; then
            wf-recorder -f "$VID" -g "$AREA"
        else
            wf-recorder -f "$VID"
        fi
    fi
}'

# VPN
riverctl map normal Super+Shift V spawn '{
    if nmcli connection show wireguard | grep activated; then
        nmcli connection down wireguard
    else
        err="$(nmcli connection up wireguard 2>&1)" && \
        notify-send "Wireguard" "Connected" || \
        notify-send -u critical "Wireguard connection failed" "$err"
    fi
} >/dev/null 2>&1'

# notifications
riverctl map normal Super+Shift M spawn "swaync-client --toggle-dnd && pkill -x waybar -RTMIN+1"
riverctl map normal Super+Shift N spawn "swaync-client --toggle-panel && pkill -x waybar -RTMIN+1"

# mounting
riverctl map normal Super B spawn "fuzzelmnt"
riverctl map normal Super+Shift B spawn "fuzzelmnt -u"

# yubikey
riverctl map normal Super A spawn "yubikey-oath-dmenu --menu-cmd \"fuzzel -d -p 'otp > '\" --clipboard --notify"

riverctl map normal Super+Alt C spawn "drop-clipboard"
riverctl map normal Super+Alt F spawn "drop-recent-files"

# view management
riverctl default-attach-mode below
riverctl map normal Super J focus-view next
riverctl map normal Super K focus-view previous
riverctl map normal Super+Shift J swap next
riverctl map normal Super+Shift K swap previous
riverctl map normal Super X close
riverctl map normal Super F toggle-fullscreen

# tag management
count=0
for i in q w e r t y u i o; do
    tags=$((1 << count))
    count=$((count + 1))
    riverctl map normal Super $i set-focused-tags $tags
    riverctl map normal Super+Shift $i set-view-tags $tags
    riverctl map normal Super+Control $i toggle-focused-tags $tags
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

riverctl rule-add -app-id "com.mattermost.Desktop" tags $((1 << 7))

# output management
riverctl map -repeat normal Super Period focus-output next
riverctl map -repeat normal Super Comma focus-output previous
riverctl map normal Super+Shift Period send-to-output -current-tags next
riverctl map normal Super+Shift Comma send-to-output -current-tags previous
riverctl set-cursor-warp on-output-change

# floating management
riverctl map normal Super Space toggle-float
riverctl map-pointer normal Super BTN_LEFT move-view
riverctl map-pointer normal Super BTN_RIGHT resize-view
riverctl rule-add -app-id "org.pulseaudio.pavucontrol" float
riverctl rule-add -app-id "flameshot" float
riverctl rule-add -app-id "blobdrop" float
riverctl rule-add -app-id "Pinentry-gtk" float

# layout config
launch -rl stacktile --inner-padding 5 --outer-padding 0 --per-tag-config --drop-empty-configs --secondary-ratio 0.65 --secondary-count 1
riverctl default-layout stacktile
riverctl map -repeat normal Super H send-layout-cmd stacktile "primary_ratio -0.05"
riverctl map -repeat normal Super L send-layout-cmd stacktile "primary_ratio +0.05"
riverctl map -repeat normal Super+Control J send-layout-cmd stacktile "secondary_ratio +0.05"
riverctl map -repeat normal Super+Control K send-layout-cmd stacktile "secondary_ratio -0.05"
riverctl map normal Super+Shift L send-layout-cmd stacktile "primary_count -1"
riverctl map normal Super+Shift H send-layout-cmd stacktile "primary_count +1"
riverctl map normal Super+Control L send-layout-cmd stacktile "secondary_count -1"
riverctl map normal Super+Control H send-layout-cmd stacktile "secondary_count +1"
riverctl map normal Super+Shift F spawn "riverctl send-layout-cmd stacktile 'all_primary true' && riverctl send-layout-cmd stacktile 'primary_sublayout full'"
riverctl map normal Super+Shift+Control F spawn "riverctl send-layout-cmd stacktile 'all_primary false' && riverctl send-layout-cmd stacktile 'primary_sublayout columns'"

# controls
for mode in normal locked; do
    riverctl map -repeat $mode Super Bracketleft spawn "pamixer --allow-boost --set-limit 150 -d 5"
    riverctl map -repeat $mode Super Bracketright spawn "pamixer --unmute --allow-boost --set-limit 150 -i 5"
    riverctl map $mode Super M spawn "pamixer --toggle-mute"
    riverctl map -repeat $mode None XF86AudioLowerVolume spawn "pamixer --allow-boost --set-limit 150 -d 5"
    riverctl map -repeat $mode None XF86AudioRaiseVolume spawn "pamixer --unmute --allow-boost --set-limit 150 -i 5"
    riverctl map $mode None XF86AudioMute spawn "pamixer --toggle-mute"
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn "brightnessctl s 5%-"
    riverctl map -repeat $mode None XF86MonBrightnessUp spawn "brightnessctl s +5%"
    riverctl map -repeat $mode Super+Shift Bracketleft spawn "brightnessctl s 5%-"
    riverctl map -repeat $mode Super+Shift Bracketright spawn "brightnessctl s +5%"
done

# disable Super when not used as modifier to prevent opening of the menu on
# nested Windows or GNOME sessions
riverctl map normal None Super_L spawn ""
riverctl map normal None Super_R spawn ""

# passthrough mode
riverctl declare-mode passthrough
riverctl map normal Super Grave enter-mode passthrough
riverctl map passthrough Super Grave enter-mode normal

# repeat rate and delay
riverctl set-repeat 75 175

# style
riverctl background-color 0x000000
riverctl border-color-focused 0x63d1f4
riverctl border-color-unfocused 0x000000
riverctl border-color-urgent 0xffff00
riverctl border-width 2

# window decoration
riverctl rule-add ssd
riverctl rule-add -title CALENDAR position 3000 30

notify-send "River" "Init executed successfully."
